apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-provider-api-deployment
  labels:
    app: identity-provider-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-provider-api
  template:
    metadata:
      labels:
        app: identity-provider-api
    spec:
      containers:
        - name: webapi
          image: identity-provider-api-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-provider-api-service
  labels:
    app: identity-provider-api
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: identity-provider-api
