FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
WORKDIR /app
EXPOSE 80
EXPOSE 443
ENV ASPNETCORE_URLS=http://*:80
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https -t


COPY SchoolApp.Feed.Api SchoolApp.Feed.Api/
COPY SchoolApp.Feed.Application SchoolApp.Feed.Application/
COPY SchoolApp.Feed.Http SchoolApp.Feed.Http/
COPY SchoolApp.Feed.NoSql SchoolApp.Feed.NoSql/
COPY SchoolApp.Feed.Queue SchoolApp.Feed.Queue/
COPY SchoolApp.Feed.Ioc SchoolApp.Feed.Ioc/

COPY SchoolApp.Shared.Utils SchoolApp.Shared.Utils/
COPY SchoolApp.Shared.Utils.MongoDb SchoolApp.Shared.Utils.MongoDb/
COPY SchoolApp.Shared.Utils.HttpApi SchoolApp.Shared.Utils.HttpApi/

RUN dotnet restore SchoolApp.Feed.Api/SchoolApp.Feed.Api.csproj
RUN dotnet build SchoolApp.Feed.Api/SchoolApp.Feed.Api.csproj
RUN dotnet publish SchoolApp.Feed.Api/SchoolApp.Feed.Api.csproj -c Release -o /app/published-app



FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
WORKDIR /app
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/SchoolApp.Feed.Api.dll" ]