FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
WORKDIR /app
EXPOSE 80
EXPOSE 443
ENV ASPNETCORE_URLS=http://*:80


COPY SchoolApp.Activity.Api SchoolApp.Activity.Api/
COPY SchoolApp.Activity.Application SchoolApp.Activity.Application/
COPY SchoolApp.Activity.Ioc SchoolApp.Activity.Ioc/
COPY SchoolApp.Activity.NoSql SchoolApp.Activity.NoSql/
COPY SchoolApp.Activity.Http SchoolApp.Activity.Http/

COPY SchoolApp.Shared.Utils SchoolApp.Shared.Utils/
COPY SchoolApp.Shared.Utils.Sql SchoolApp.Shared.Utils.Sql/
COPY SchoolApp.Shared.Utils.HttpApi SchoolApp.Shared.Utils.HttpApi/
COPY SchoolApp.Shared.Utils.MongoDb SchoolApp.Shared.Utils.MongoDb/

RUN dotnet restore SchoolApp.Activity.Api/SchoolApp.Activity.Api.csproj
RUN dotnet build SchoolApp.Activity.Api/SchoolApp.Activity.Api.csproj
RUN dotnet publish SchoolApp.Activity.Api/SchoolApp.Activity.Api.csproj -c Release -o /app/published-app
RUN dotnet dev-certs https


FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
WORKDIR /app
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/SchoolApp.Activity.Api.dll" ]