FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build
WORKDIR /app
EXPOSE 80
EXPOSE 443
ENV ASPNETCORE_URLS=http://*:80
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https -t

COPY SchoolApp.Classroom.ServiceApi SchoolApp.Classroom.ServiceApi/
COPY SchoolApp.Classroom.Application SchoolApp.Classroom.Application/
COPY SchoolApp.Classroom.Ioc SchoolApp.Classroom.Ioc/
COPY SchoolApp.Classroom.Sql SchoolApp.Classroom.Sql/
COPY SchoolApp.Classroom.Http SchoolApp.Classroom.Http/

COPY SchoolApp.Shared.Utils SchoolApp.Shared.Utils/
COPY SchoolApp.Shared.Utils.Sql SchoolApp.Shared.Utils.Sql/
COPY SchoolApp.Shared.Utils.HttpApi SchoolApp.Shared.Utils.HttpApi/

RUN dotnet restore SchoolApp.Classroom.ServiceApi/SchoolApp.Classroom.ServiceApi.csproj
RUN dotnet build SchoolApp.Classroom.ServiceApi/SchoolApp.Classroom.ServiceApi.csproj
RUN dotnet publish SchoolApp.Classroom.ServiceApi/SchoolApp.Classroom.ServiceApi.csproj -c Release -o /app/published-app



FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime
WORKDIR /app
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/SchoolApp.Classroom.ServiceApi.dll" ]