CREATE DATABASE IdentityProvider
GO
USE IdentityProvider
GO
CREATE TABLE [Owner]
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name NVARCHAR(400) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	Password NVARCHAR(200) NOT NULL,
	DocumentId NVARCHAR(100) NULL,
	IsMainOwner BIT NOT NULL,
	CreatorId INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	UpdaterId INT NULL,
	UpdateDate DATETIME NULL,
	Deleted BIT NOT NULL
)
GO
CREATE TABLE [Teacher]
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name NVARCHAR(400) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	Password NVARCHAR(200) NOT NULL,
	DocumentId NVARCHAR(100) NULL,
	AcademicFormation NVARCHAR(200) NULL,
	Salary DECIMAL(18, 2) NOT NULL,
	HiringDate DATETIME NOT NULL,
	CreatorId INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	UpdaterId INT NULL,
	UpdateDate DATETIME NULL,
	Deleted BIT NOT NULL
)
GO
CREATE TABLE [Manager]
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name NVARCHAR(400) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	Password NVARCHAR(200) NOT NULL,
	DocumentId NVARCHAR(100) NULL,
	AcademicFormation NVARCHAR(200) NULL,
	Salary DECIMAL(18, 2) NOT NULL,
	HiringDate DATETIME NOT NULL,
	FunctionId INT NOT NULL,
	CreatorId INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	UpdaterId INT NULL,
	UpdateDate DATETIME NULL,
	Deleted BIT NOT NULL
)
GO
CREATE TABLE [Function] 
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	Description NVARCHAR(400) NULL,
	CreatorId INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	UpdaterId INT NULL,
	UpdateDate DATETIME NULL
)
GO
-- SET FOREIGN KEYS RELATIONS
ALTER TABLE Manager ADD CONSTRAINT [FK_Manager_FunctionId] FOREIGN KEY (FunctionId) REFERENCES [Function](Id)
GO
-- SET INDEXES TO PERFORMANCE
CREATE NONCLUSTERED INDEX IX_Teacher_Email ON [Teacher](Email)
GO
CREATE NONCLUSTERED INDEX IX_Manager_Email ON [Manager](Email)
GO
CREATE NONCLUSTERED INDEX IX_Owner_Email ON [Owner](Email)
GO




