apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-mongodb-deployment
  labels:
    app: activity-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-mongodb
  template:
    metadata:
      labels:
        app: activity-mongodb
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "1SenhaForte@"
---
apiVersion: v1
kind: Service
metadata:
  name: activity-mongodb-service
spec:
  selector:
    app: activity-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer